name: httpstat # you probably want to 'snapcraft register <name>'
version: '1.1.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: curl stats made simple # 79 char long summary
description: |
  this version of httpstat is packed with an old version of Python downloaded as a separate part and built with autotools plugin (no python plugin at all).

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  httpstat:
    command: bin/httpstat/httpstat.py
    plugs: [network]

parts:
  httpstat:
    source: .
    plugin: dump
    after: [python]
  python:
    plugin: autotools
    source: https://github.com/python/cpython.git
    source-type: git
    source-tag: v2.7.12
    configflags: [--prefix=/usr]
    build-packages: [libssl-dev]
    stage-packages: [curl]
    prime:  #raise "IOError invalid Python installation unable to open /snap/httpstat/x1/usr/include/python2.7/pyconfig.h (No such file or directory)" with 2.7.4 and earlier
      - -usr/include  #python 2.7.4 and earlier work well without that line (seem work well without above 2.7.4 too)
