name: httpstat # you probably want to 'snapcraft register <name>'
version: '1.1.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: curl stats made simple # 79 char long summary
description: |
  httpstat tool description

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  httpstat:
    command: httpstat

parts:
  python:
    plugin: python
    python-version: python2
    stage-packages: [curl]
  httpstat:
    source: .
    plugin: dump
